#!/usr/bin/bash
shopt -s globstar

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DOTDIR="~/.dotfiles"

mkdir -p $DOTDIR
ln -s $DIR/update_public $DOTDIR/
ln -s $DIR/update $DOTDIR/

cd $DOTDIR && ./update_public    
